#pragma once
#define MAXDIRECTNAME 14
#define MAXOWNERLENGTH 20
#define DIRECTNUM 32
#define MAXGROUPLENGTH 20
#define BLOCKSIZE 512
#define STACKSIZE 20
#define INODEBLOCKNUM 40
#define DATABLOCKNUM 800
#define PERINODESIZE 128
#define TOTALINODENUM 160
#define BLOCKSTART 42